apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  labels:
    app: keycloak
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080  # External port you can access
    - name: https
      port: 9443
      targetPort: 9443
      nodePort: 30443
    - name: management
      port: 10990
      targetPort: 10990
      nodePort: 30990
