apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # This matches the app label in the Deployment
  ports:
    - protocol: TCP
      port: 80       # Expose port 80 for external access
      targetPort: 80 # Port on the NGINX container
      nodePort: 30000  # Specify the port on the node (optional, Kubernetes will assign it automatically if not specified)
  type: NodePort  # Use NodePort to expose the service externally on each node's IP
